### ISSUE TITLE
Have a deal with mime-boundary answers

### ISSUE THREAD

**Issue by viktorprogger** [meng-tian/php-soap-interpreter#16]
Some SOAP servers answers in mime-boundary format. It is ok for SOAP generally, but php's soap client don't understand this. I didn't see a good way to solve this, but [here is a working one](https://stackoverflow.com/questions/14622830/proper-way-to-parse-multipart-soap-attachments#answer-14649199).

**Comment by realmtian** [comment]
Thanks for raising this issue the proposed PR.

As you may notice this is more of a problem for PHP's SoapClient rather than this library. I'd say this is something should be fixed by PHP.

If you later find letting PHP fix this is too slow or difficult, I would recommend to support multi-part attachments in the application code instead.

**Comment by viktorprogger** [comment]
This is a bug in `SoapClient`, yes. [It is registered 13 years ago](https://pear.php.net/bugs/bug.php?id=9538) and wasn't fixed yet.

**Comment by viktorprogger** [comment]
[There is a bug](https://bugs.php.net/bug.php?id=47810) 10 years old

**Comment by realmtian** [comment]
That's bad :(
Then again I would recommend support multi-part attachments in your application code instead. This library is intended to just mimic what is available from PHP's SoapClient without surprises.

**Comment by viktorprogger** [comment]
Sad to hear this. `meng-tian/async-soap-guzzle` is not extendable, so I had to create my own copy of 3 your packages to solve this issue in my project :(
